-- Non-destructive migration: global pH readings are independent from
-- per-bedengan sensor_readings. Existing mixed legacy readings are preserved.
begin;

create table if not exists public.soil_ph_readings (
  id bigint generated by default as identity primary key,
  ph_value numeric(5,2) not null check (ph_value >= 0 and ph_value <= 14),
  measured_at timestamptz not null default timezone('utc', now())
);

create index if not exists soil_ph_readings_measured_at_idx
  on public.soil_ph_readings (measured_at desc);

commit;
